# Generated by Django 3.0 on 2020-08-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werespond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
