# Generated by Django 3.0 on 2020-08-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werespond', '0002_auto_20200806_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
