# Generated by Django 3.0 on 2020-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werespond', '0003_auto_20200806_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.CharField(max_length=3000),
        ),
    ]
